---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tchap-web.fullname" . }}
  labels:
    {{- include "tchap-web.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.config | nindent 4}}
